src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity
 */
class Product
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var int|null
     *
     * @ORM\Column(name="price", type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=ProductType::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $productType;

    /**
     * @ORM\OneToOne(targetEntity=FoodInfo::class, cascade={"persist", "remove"})
     */
    private $food_info;

    /**
     * @ORM\OneToOne(targetEntity=DrinkInfo::class, cascade={"persist", "remove"})
     */
    private $drink_info;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=TypeCategory::class)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getProductType(): ?ProductType
    {
        return $this->productType;
    }

    public function setProductType(?ProductType $productType): self
    {
        $this->productType = $productType;

        return $this;
    }

    public function getFoodInfo(): ?FoodInfo
    {
        return $this->food_info;
    }

    public function setFoodInfo(?FoodInfo $food_info): self
    {
        $this->food_info = $food_info;

        return $this;
    }

    public function getDrinkInfo(): ?DrinkInfo
    {
        return $this->drink_info;
    }

    public function setDrinkInfo(?DrinkInfo $drink_info): self
    {
        $this->drink_info = $drink_info;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?TypeCategory
    {
        return $this->category;
    }

    public function setCategory(?TypeCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

}

src/Entity/ProductType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * ProductType
 *
 * @ORM\Table(name="product_type")
 * @ORM\Entity
 */
class ProductType
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=TypeCategory::class, mappedBy="productType")
     */
    private $category;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|TypeCategory[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(TypeCategory $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
            $category->setProductType($this);
        }

        return $this;
    }

    public function removeCategory(TypeCategory $category): self
    {
        if ($this->category->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getProductType() === $this) {
                $category->setProductType(null);
            }
        }

        return $this;
    }


}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Content;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Product;
use App\Entity\ProductType;


class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="product")
     */
    public function index(): Response
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findAll();
        $types = $this->getDoctrine()->getRepository(ProductType::class)->findAll();
        $contents = $this->getDoctrine()->getRepository(Content::class)->findAll();

        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'products' => $products,
            'types' => $types,
            'contents' => $contents
        ]);
    }

    /**
     * @Route("/produits/categorie/{category}", name="productByCategory")
     */
    public function productByCategory(string $category): Response
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findByCategory($category);
        $types = $this->getDoctrine()->getRepository(ProductType::class)->findAll();
        $contents = $this->getDoctrine()->getRepository(Content::class)->findAll();

        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'products' => $products,
            'types' => $types,
            'contents' => $contents
        ]);
    }

    /**
     * @Route("/produits/type/{type}", name="productByType")
     */
    public function productByType(string $type): Response
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findByProductType($type);
        $types = $this->getDoctrine()->getRepository(ProductType::class)->findAll();
        $contents = $this->getDoctrine()->getRepository(Content::class)->findAll();

        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'products' => $products,
            'types' => $types,
            'contents' => $contents
        ]);
    }

    /**
     * @Route("/products/{id}", name="product")
     */
    public function productDetails($id): Response
    {
        $product = $this->getDoctrine()->getRepository(Product::class)->find($id);
        $types = $this->getDoctrine()->getRepository(ProductType::class)->findAll();
        $contents = $this->getDoctrine()->getRepository(Content::class)->findAll();

        return $this->render('product/details.html.twig', [
            'controller_name' => 'ProductController',
            'product' => $product,
            'types' => $types,
            'contents' => $contents
        ]);
    }
}

templates/product/details.html.twig
{% extends 'base-public.html.twig' %}

{% block title %}{{product.name}}{% endblock %}

{% block body %}

<main class="product">
  <section id="product-header">
    <div class="product-image">
      <img src="{{asset('assets/img/products/'~ product.image)}}" />
    </div>
    <div class="product-title-desc">
      <h1>{{product.name}}</h1>
      <span>
        <span class="type">{{ product.productType.name }}</span>
        <span class="category">{{ product.category.name }}</span>
        {% if product.drinkInfo %}
          <span class="drinktype">{% for info in product.drinkInfo.type %}{{ info.name }} {% endfor %}</span>
        {% endif %}
      </span>
       <p>{{product.description}}</p>
         
      {% if product.foodInfo %}
        <h3>Infos nutritions</h3>
          <ul class="food-info">
              <li>Matières grasses : {{ product.foodInfo.fat }}g</li>
              <li>Valeur énergétique : {{ product.foodInfo.energy }}kcal</li>
              <li>Glucides : {{ product.foodInfo.glucid }}g</li>
              <li>Protéines : {{ product.foodInfo.protein }}g</li>
              <li>Sucre : {{ product.foodInfo.sugar }}g</li>
              <li>Sel : {{ product.foodInfo.salt }}g</li>
          </ul>
      {% endif %}

      {% if product.drinkInfo %}
        <h3>Infos Boisson</h3>
          <ul class="food-info">
              <li>Litre : {{ product.drinkInfo.liter }} litre(s)</li>
              <li>Alcool : {{ product.drinkInfo.alcohol }}°</li>
          </ul>
      {% endif %}

      <button>
        <a href="{{ path('panier_add', {'id': product.id}) }}">Ajouter au panier - <span class="price">{{product.price}}€</span></a>
      </button>
    </div>
  </section>
</main>

{% endblock %}

templates/product/index.html.twig
{% extends 'base-public.html.twig' %}

{% block title %}EatOrder - La Cave & Vous{% endblock %}

{% block body %}

<main class="products">
    
    <div class="flex-products">
        {% for product in products %}  
        
        <article style="background-image: url('{{asset('assets/img/products/'~ product.image)}}');">
            <a href="{{ path('product', {'id': product.id}) }}"> 
                <h3>{{product.name}}</h3>
            </a>
        </article>

        {% endfor %}
    </div>

</main>

{% endblock %}